### ISSUE TITLE
Radiation in Space

### ISSUE THREAD

**Issue by Hecatia-Lapislazuli** [egladil/oni-nubrion#1]
Radiation appears to interact weirdly in the vacuum of space, may be an issue on Clay's side as well, but didn't go into enough testing. Basically, when you vent out helium (may be more, but only tested helium) into space, radiation spreads to vacuum tiles, as well. I was using non-lead pipes, so that may be part of what is causing this.

The solution I thought of is to just make 100% radiation germs die while in vacuum or something to that nature.

Also, it may be worth making space exposure give radiation as it's own mod, think that might be a bit fun of a challenge to have, if you're not using the... Empty Worlds mod, I think. That's part of why I found this in the first place.

**Comment by RasmusFey** [comment]
That should happen, at least irl. "Nuclear radiation" describes ionizing subatomic particles found in radioactive decay such as ionized Helium-4(Alpha particles), high speed electrons(Beta particles) and neutrons. Ionizing radiation is radiation that carries sufficient energy to detach electrons from atoms or molecules, thereby ionizing them.
And those particles just dance around in space. See? Completley normal.

**Comment by Hecatia-Lapislazuli** [comment]
Yeah, irl it would happen to an extent, but when the game has 1 billion on each tile of space, it's a bit much. I mean, you can lead shield everything you build, I suppose, however besides doing that there isn't really a way to combat it as it pretty much instantly spreads to everything due to how much radiation there is. 

Pure speculation on this part, but I'd suspect that even with lead shielding and lead doors, radiation would still manage to enter into your own base unless you had a food poisoning infested polluted water entrance to prevent the spread of the radiation from the oxygen you'd have leaking out. 

IRL you could at least wait for them to decay naturally. I'm suspecting due to the manner ONI handles vacuum, it is bugging out kinda and multiplying the amount of germs when they spread, meaning the half life becomes, in essence, inconsequential to the amount of radiation being produced from nothing.

**Comment by egladil** [comment]
The unlimited growth of radiation in vacuum was unintentional, I had simply forgot to set a half life there. I've updated it to use the same half life as radiation in gas for now. Might tweak the numbers a bit in the future

Having space exposure cause spontaenous radiation sounds like an interesting idea. It would probably have to be quite a low amount so you don't instantly get radiation in your entire base when you venture out into space
