### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by Fatmice** [egladil/oni-nubrion#12]
Hello,
Could you comment out these lines?

https://github.com/egladil/oni-mods/blob/7fd2627a8c2d71c43d51709d8d39841fdc764f6d/FusionReactor/FusionReactor.cs#L228
https://github.com/egladil/oni-mods/blob/c10e97a8d5ab030c2d4e4a3f35e2f32d8397fed7/GigawattWire/ExtendedWire.cs#L230
https://github.com/egladil/oni-mods/blob/c10e97a8d5ab030c2d4e4a3f35e2f32d8397fed7/GigawattWire/ExtendedWire.cs#L287

They are especially aggregious and fill up hundreds of megabytes of the log.

**Comment by egladil** [comment]
I accidentally uploaded a build where this was set to true. Recompiled and reuploaded
https://github.com/egladil/oni-mods/blob/c10e97a8d5ab030c2d4e4a3f35e2f32d8397fed7/Shared/Log.cs#L11
