### ISSUE TITLE
5 KW Wire Bug

### ISSUE THREAD

**Issue by LonesomePlayer** [egladil/oni-nubrion#7]
Got since yesterday the following Bug: The 5 KW Cable is replace in the building menu with the picture but the text is " Missing.Strings.Buildings.Prefabs.Jacketedwire.Effect" applies too on the bridge´s & the heavy variant... on the other Side, no crash, build & deconstruct work´s & is working
![Wire](https://user-images.githubusercontent.com/62025242/82926825-09f67b00-9f80-11ea-91d3-336d83d4642b.jpg)

**Comment by ghost** [comment]
Was about to post this, it's not just the 5KW wire, it's all wires, transformers, and joint plates from both tiers in the mod that are missing strings for both Name and Effect in the UI.  No errors in the log and everything seems to be working in my sandbox testing though.

**Comment by egladil** [comment]
This seems to have been a temporary issue due to one of Klei's updates, doesn't seem to happen any more
