### ISSUE TITLE
Mod crashes

### ISSUE THREAD

**Issue by tropus1** [egladil/oni-nubrion#9]
With the last update, the game crashed when the game load.

**Comment by tropus1** [comment]
here is the error from my output_log
MissingMethodException: string GameUtil.GetWireLoadColor(single,single)
at StatusItem.ResolveString (System.String str, System.Object data) [0x0000b] in <9c6cad35fa814f4e9b7adf3604ce8e0c>:0
at StatusItem.GetName (System.Object data) [0x00000] in <9c6cad35fa814f4e9b7adf3604ce8e0c>:0
at StatusItemGroup+Entry.GetName () [0x00000] in <9c6cad35fa814f4e9b7adf3604ce8e0c>:0
at SelectToolHoverTextCard.UpdateHoverElements (System.Collections.Generic.List`1[T] hoverObjects) [0x01231] in <9c6cad35fa814f4e9b7adf3604ce8e0c>:0
at InterfaceTool.UpdateHoverElements (System.Collections.Generic.List`1[T] hits) [0x0000e] in <9c6cad35fa814f4e9b7adf3604ce8e0c>:0
at InterfaceTool.LateUpdate () [0x0006f] in <9c6cad35fa814f4e9b7adf3604ce8e0c>:0

**Comment by Fatmice** [comment]
Crashes on AP-419840-D

**Comment by geonmo** [comment]
I created a PR #10 to fix this problem.

**Comment by Fatmice** [comment]
@geonmo Can you look into #6? 
```System.TypeInitializationException: The type initializer for 'Egladil.RadiationGerms' threw an exception. ---> System.MissingFieldException: Field 'DiseaseVisualization/Info.overlayColour' not found.```

May be an easy fix by just using the right function from the game? This might enable Fusion reactor mod to work again.

If do able, I might try and fork this repo and recompile the mods. I do not know much about ONI's modding API.

**Comment by geonmo** [comment]
@Fatmice Ok, I will also check the fusion reactor and the radiation mods. Before that, I think we need to check if this GigawattWire mod is working on other people's computers.  Please install the mod in the order below and check if it works properly. 

1. Go to the [link](https://drive.google.com/drive/folders/1NUNTqaenH2vEhWDMaYcyyRf6MwUSsBWD?usp=sharing) and download the GigawattWire.zip file.
2. Go to %USERPROFILE%\Documents\Klei\OxygenNotIncluded\mods\dev on windows explorer and extract. Once a directory called GigawattWire is created, it is a success.
3. Run the ONI, disable the existing steam version, and try to turn on the local version in the list.
4. Play the game and make sure it works properly.

On my computer,, there were no "mods" and "dev" directories under the "OxygenNotIncluded" directory, so I made it. I think it works that it's in the right position.

If it doesn't work, it's meaningless, so please check it.

**Comment by daniellom30** [comment]
Hello, try the local mod (% USERPROFILE% \ Documents \ Klei \ OxygenNotIncluded \ mods \ dev) and it works correctly, thank you very much, it would be nice to upload this corrected version to steam

**Comment by egladil** [comment]
Should be fixed in the steam workshop version of the mod as well
